export default {
  key: 'stack',
  name: '应用管理',
  path: '/stack',
  group: 1,
  admin: false,
  user: true,
  childs: [{
    key: "list",
    name: "我的应用",
    path: "/list",
    admin: false,
    user: true,
  }, {
    key: "balance",
    name: "负载均衡",
    path: "/balance",
    admin: false,
    user: true,
  }, {
    key: "secret",
    name: "证书列表",
    path: "/secret",
    admin: false,
    user: true,
  }, {
    key: "configmap",
    name: "配置管理",
    path: "/configmap",
    admin: false,
    user: true,
  }, {
    key: "topology",
    name: "拓扑图",
    path: "/topology",
    admin: false,
    user: true,
  }]
}